return {
  -- Enhanced file explorer with modern icons
  {
    "snacks.nvim",
    opts = {
      explorer = {
        -- Use modern rounded icons
        icons = {
          folder = {
            closed = "󰉋",
            open = "󰝰",
            empty = "󰉖",
            empty_open = "󰷏",
            symlink = "󰉒",
            symlink_open = "󰉒",
          },
          file = {
            default = "󰈙",
            symlink = "󰌹",
            executable = "󰈸",
          },
          git = {
            unstaged = "󰄱",
            staged = "󰱒",
            unmerged = "󰘭",
            renamed = "󰑕",
            untracked = "󰈤",
            deleted = "󰍵",
            ignored = "󰘓",
          },
        },
      },
    },
  },
  -- Override mini.icons with Helium-style icons
  {
    "echasnovski/mini.icons",
    opts = {
      -- File type icons with modern look
      file = {
        [".gitignore"] = { glyph = "󰊢", hl = "MiniIconsGrey" },
        [".gitattributes"] = { glyph = "󰊢", hl = "MiniIconsGrey" },
        [".env"] = { glyph = "󰙄", hl = "MiniIconsYellow" },
        [".dockerignore"] = { glyph = "󰡨", hl = "MiniIconsBlue" },
        ["dockerfile"] = { glyph = "󰡨", hl = "MiniIconsBlue" },
        ["docker-compose.yml"] = { glyph = "󰡨", hl = "MiniIconsBlue" },
        ["package.json"] = { glyph = "󰎙", hl = "MiniIconsGreen" },
        ["package-lock.json"] = { glyph = "󰎙", hl = "MiniIconsGreen" },
        ["tsconfig.json"] = { glyph = "󰛦", hl = "MiniIconsBlue" },
        ["webpack.config.js"] = { glyph = "󰜫", hl = "MiniIconsBlue" },
        ["vite.config.js"] = { glyph = "󱐋", hl = "MiniIconsPurple" },
        ["rollup.config.js"] = { glyph = "󰑣", hl = "MiniIconsRed" },
        ["README.md"] = { glyph = "󰍔", hl = "MiniIconsBlue" },
        ["CHANGELOG.md"] = { glyph = "󰉻", hl = "MiniIconsGreen" },
        ["LICENSE"] = { glyph = "󰿃", hl = "MiniIconsYellow" },
        ["yarn.lock"] = { glyph = "󰎙", hl = "MiniIconsBlue" },
        ["pnpm-lock.yaml"] = { glyph = "󰎙", hl = "MiniIconsOrange" },
        ["bun.lockb"] = { glyph = "󰎙", hl = "MiniIconsOrange" },
        [".nvmrc"] = { glyph = "󰎙", hl = "MiniIconsGreen" },
        ["vercel.json"] = { glyph = "󰔶", hl = "MiniIconsBlue" },
        ["netlify.toml"] = { glyph = "󰔷", hl = "MiniIconsGreen" },
        ["next.config.js"] = { glyph = "󰰓", hl = "MiniIconsBlue" },
        ["nuxt.config.js"] = { glyph = "󰰓", hl = "MiniIconsGreen" },
        ["svelte.config.js"] = { glyph = "󰰓", hl = "MiniIconsOrange" },
        ["tailwind.config.js"] = { glyph = "󱏿", hl = "MiniIconsBlue" },
        ["postcss.config.js"] = { glyph = "󰰓", hl = "MiniIconsRed" },
        ["prettier.config.js"] = { glyph = "󰬗", hl = "MiniIconsPurple" },
        [".prettierrc"] = { glyph = "󰬗", hl = "MiniIconsPurple" },
        [".eslintrc.js"] = { glyph = "󰱺", hl = "MiniIconsPurple" },
        [".eslintrc.json"] = { glyph = "󰱺", hl = "MiniIconsPurple" },
        ["jest.config.js"] = { glyph = "󰙨", hl = "MiniIconsRed" },
        ["vitest.config.js"] = { glyph = "󰙨", hl = "MiniIconsGreen" },
        ["cypress.config.js"] = { glyph = "󰙨", hl = "MiniIconsGreen" },
        ["playwright.config.js"] = { glyph = "󰙨", hl = "MiniIconsBlue" },
        ["storybook.config.js"] = { glyph = "󰙨", hl = "MiniIconsPurple" },
        ["angular.json"] = { glyph = "󰚿", hl = "MiniIconsRed" },
        ["vue.config.js"] = { glyph = "󰰓", hl = "MiniIconsGreen" },
        ["remix.config.js"] = { glyph = "󰰓", hl = "MiniIconsBlue" },
        ["astro.config.js"] = { glyph = "󰰓", hl = "MiniIconsOrange" },
        ["go.mod"] = { glyph = "󰟓", hl = "MiniIconsBlue" },
        ["go.sum"] = { glyph = "󰟓", hl = "MiniIconsBlue" },
        ["Cargo.toml"] = { glyph = "󱘗", hl = "MiniIconsOrange" },
        ["Cargo.lock"] = { glyph = "󱘗", hl = "MiniIconsOrange" },
        ["requirements.txt"] = { glyph = "󰌠", hl = "MiniIconsBlue" },
        ["pyproject.toml"] = { glyph = "󰌠", hl = "MiniIconsBlue" },
        ["Pipfile"] = { glyph = "󰌠", hl = "MiniIconsBlue" },
        ["poetry.lock"] = { glyph = "󰌠", hl = "MiniIconsBlue" },
        ["Gemfile"] = { glyph = "󰴭", hl = "MiniIconsRed" },
        ["Gemfile.lock"] = { glyph = "󰴭", hl = "MiniIconsRed" },
        ["composer.json"] = { glyph = "󰈗", hl = "MiniIconsPurple" },
        ["composer.lock"] = { glyph = "󰈗", hl = "MiniIconsPurple" },
        ["pubspec.yaml"] = { glyph = "󰈗", hl = "MiniIconsBlue" },
        ["pubspec.lock"] = { glyph = "󰈗", hl = "MiniIconsBlue" },
        ["build.gradle"] = { glyph = "󰘺", hl = "MiniIconsBlue" },
        ["pom.xml"] = { glyph = "󰘺", hl = "MiniIconsOrange" },
        ["CMakeLists.txt"] = { glyph = "󰰒", hl = "MiniIconsBlue" },
        ["Makefile"] = { glyph = "󰰒", hl = "MiniIconsGreen" },
        ["makefile"] = { glyph = "󰰒", hl = "MiniIconsGreen" },
        ["*.mk"] = { glyph = "󰰒", hl = "MiniIconsGreen" },
      },
      -- Extension icons with modern look
      extension = {
        js = { glyph = "󰌞", hl = "MiniIconsYellow" },
        jsx = { glyph = "", hl = "MiniIconsBlue" },
        ts = { glyph = "󰛦", hl = "MiniIconsBlue" },
        tsx = { glyph = "", hl = "MiniIconsBlue" },
        vue = { glyph = "󰡄", hl = "MiniIconsGreen" },
        svelte = { glyph = "󰰓", hl = "MiniIconsOrange" },
        astro = { glyph = "󰰓", hl = "MiniIconsOrange" },
        html = { glyph = "󰌝", hl = "MiniIconsOrange" },
        css = { glyph = "󰌜", hl = "MiniIconsBlue" },
        scss = { glyph = "󰟦", hl = "MiniIconsPurple" },
        sass = { glyph = "󰟦", hl = "MiniIconsPurple" },
        less = { glyph = "󰰒", hl = "MiniIconsBlue" },
        stylus = { glyph = "󰰒", hl = "MiniIconsGreen" },
        json = { glyph = "󰘦", hl = "MiniIconsYellow" },
        yaml = { glyph = "", hl = "MiniIconsOrange" },
        yml = { glyph = "", hl = "MiniIconsOrange" },
        toml = { glyph = "󰘦", hl = "MiniIconsOrange" },
        xml = { glyph = "󰘦", hl = "MiniIconsOrange" },
        py = { glyph = "󰌠", hl = "MiniIconsBlue" },
        rb = { glyph = "󰴭", hl = "MiniIconsRed" },
        php = { glyph = "󰌟", hl = "MiniIconsPurple" },
        go = { glyph = "󰟓", hl = "MiniIconsBlue" },
        rs = { glyph = "󱘗", hl = "MiniIconsOrange" },
        java = { glyph = "󰬷", hl = "MiniIconsOrange" },
        kt = { glyph = "󱈙", hl = "MiniIconsPurple" },
        swift = { glyph = "󰛥", hl = "MiniIconsOrange" },
        c = { glyph = "󰙱", hl = "MiniIconsBlue" },
        cpp = { glyph = "󰙲", hl = "MiniIconsBlue" },
        h = { glyph = "󰙱", hl = "MiniIconsBlue" },
        hpp = { glyph = "󰙲", hl = "MiniIconsBlue" },
        cs = { glyph = "󰌛", hl = "MiniIconsPurple" },
        fs = { glyph = "󰈖", hl = "MiniIconsBlue" },
        ml = { glyph = "󰈖", hl = "MiniIconsOrange" },
        lua = { glyph = "󰢱", hl = "MiniIconsBlue" },
        vim = { glyph = "󰕷", hl = "MiniIconsGreen" },
        sh = { glyph = "", hl = "MiniIconsGreen" },
        bash = { glyph = "󰑓", hl = "MiniIconsGreen" },
        zsh = { glyph = "󰑓", hl = "MiniIconsGreen" },
        fish = { glyph = "󰑓", hl = "MiniIconsGreen" },
        ps1 = { glyph = "󰑓", hl = "MiniIconsBlue" },
        bat = { glyph = "󰑓", hl = "MiniIconsBlue" },
        cmd = { glyph = "󰑓", hl = "MiniIconsBlue" },
        dart = { glyph = "", hl = "MiniIconsBlue" },
        sql = { glyph = "󰆼", hl = "MiniIconsBlue" },
        prisma = { glyph = "󰆼", hl = "MiniIconsBlue" },
        graphql = { glyph = "󰡷", hl = "MiniIconsPurple" },
        gql = { glyph = "󰡷", hl = "MiniIconsPurple" },
        md = { glyph = "󰍔", hl = "MiniIconsBlue" },
        mdx = { glyph = "󰍔", hl = "MiniIconsBlue" },
        txt = { glyph = "󰈙", hl = "MiniIconsGrey" },
        pdf = { glyph = "󰈦", hl = "MiniIconsRed" },
        doc = { glyph = "󰈙", hl = "MiniIconsBlue" },
        docx = { glyph = "󰈙", hl = "MiniIconsBlue" },
        xls = { glyph = "󰈙", hl = "MiniIconsGreen" },
        xlsx = { glyph = "󰈙", hl = "MiniIconsGreen" },
        ppt = { glyph = "󰈙", hl = "MiniIconsOrange" },
        pptx = { glyph = "󰈙", hl = "MiniIconsOrange" },
        zip = { glyph = "󰗄", hl = "MiniIconsYellow" },
        rar = { glyph = "󰗄", hl = "MiniIconsYellow" },
        ["7z"] = { glyph = "󰗄", hl = "MiniIconsYellow" },
        tar = { glyph = "󰗄", hl = "MiniIconsYellow" },
        gz = { glyph = "󰗄", hl = "MiniIconsYellow" },
        png = { glyph = "󰉏", hl = "MiniIconsPurple" },
        jpg = { glyph = "󰉏", hl = "MiniIconsPurple" },
        jpeg = { glyph = "󰉏", hl = "MiniIconsPurple" },
        gif = { glyph = "󰉏", hl = "MiniIconsPurple" },
        svg = { glyph = "󰉏", hl = "MiniIconsYellow" },
        webp = { glyph = "󰉏", hl = "MiniIconsPurple" },
        ico = { glyph = "󰉏", hl = "MiniIconsPurple" },
        mp4 = { glyph = "󰕧", hl = "MiniIconsRed" },
        avi = { glyph = "󰕧", hl = "MiniIconsRed" },
        mov = { glyph = "󰕧", hl = "MiniIconsRed" },
        mkv = { glyph = "󰕧", hl = "MiniIconsRed" },
        mp3 = { glyph = "󰝚", hl = "MiniIconsYellow" },
        wav = { glyph = "󰝚", hl = "MiniIconsYellow" },
        flac = { glyph = "󰝚", hl = "MiniIconsYellow" },
        ogg = { glyph = "󰝚", hl = "MiniIconsYellow" },
        woff = { glyph = "󰛖", hl = "MiniIconsGrey" },
        woff2 = { glyph = "󰛖", hl = "MiniIconsGrey" },
        ttf = { glyph = "󰛖", hl = "MiniIconsGrey" },
        otf = { glyph = "󰛖", hl = "MiniIconsGrey" },
        eot = { glyph = "󰛖", hl = "MiniIconsGrey" },
      },
      -- Directory icons with modern look
      directory = {
        [".git"] = { glyph = "󰊢", hl = "MiniIconsGrey" },
        [".github"] = { glyph = "󰊢", hl = "MiniIconsGrey" },
        [".vscode"] = { glyph = "󰨞", hl = "MiniIconsBlue" },
        [".idea"] = { glyph = "󰺷", hl = "MiniIconsOrange" },
        ["node_modules"] = { glyph = "󰎙", hl = "MiniIconsRed" },
        ["dist"] = { glyph = "󰉖", hl = "MiniIconsYellow" },
        ["build"] = { glyph = "󰉖", hl = "MiniIconsYellow" },
        ["out"] = { glyph = "󰉖", hl = "MiniIconsYellow" },
        ["target"] = { glyph = "󰉖", hl = "MiniIconsYellow" },
        ["bin"] = { glyph = "󰉖", hl = "MiniIconsYellow" },
        ["obj"] = { glyph = "󰉖", hl = "MiniIconsYellow" },
        ["src"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["lib"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["assets"] = { glyph = "󰉋", hl = "MiniIconsPurple" },
        ["static"] = { glyph = "󰉋", hl = "MiniIconsPurple" },
        ["public"] = { glyph = "󰉋", hl = "MiniIconsPurple" },
        ["components"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["pages"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["views"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["layouts"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["templates"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["styles"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["css"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["scss"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["sass"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["images"] = { glyph = "󰉋", hl = "MiniIconsPurple" },
        ["img"] = { glyph = "󰉋", hl = "MiniIconsPurple" },
        ["icons"] = { glyph = "󰉋", hl = "MiniIconsPurple" },
        ["fonts"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["docs"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["doc"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["documentation"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["test"] = { glyph = "󰉋", hl = "MiniIconsGreen" },
        ["tests"] = { glyph = "󰉋", hl = "MiniIconsGreen" },
        ["spec"] = { glyph = "󰉋", hl = "MiniIconsGreen" },
        ["specs"] = { glyph = "󰉋", hl = "MiniIconsGreen" },
        ["__tests__"] = { glyph = "󰉋", hl = "MiniIconsGreen" },
        ["__test__"] = { glyph = "󰉋", hl = "MiniIconsGreen" },
        ["config"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["configs"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["configuration"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["utils"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["util"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["helpers"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["helper"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["scripts"] = { glyph = "󰉋", hl = "MiniIconsGreen" },
        ["script"] = { glyph = "󰉋", hl = "MiniIconsGreen" },
        ["tools"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["tool"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["types"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["type"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["typings"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["models"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["model"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["services"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["service"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["api"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["apis"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["routes"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["route"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["router"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["routers"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["controllers"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["controller"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["middlewares"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["middleware"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["plugins"] = { glyph = "󰉋", hl = "MiniIconsPurple" },
        ["plugin"] = { glyph = "󰉋", hl = "MiniIconsPurple" },
        ["extensions"] = { glyph = "󰉋", hl = "MiniIconsPurple" },
        ["extension"] = { glyph = "󰉋", hl = "MiniIconsPurple" },
        ["modules"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["module"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["packages"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["package"] = { glyph = "󰉋", hl = "MiniIconsBlue" },
        ["vendors"] = { glyph = "󰉋", hl = "MiniIconsRed" },
        ["vendor"] = { glyph = "󰉋", hl = "MiniIconsRed" },
        ["third_party"] = { glyph = "󰉋", hl = "MiniIconsRed" },
        ["thirdparty"] = { glyph = "󰉋", hl = "MiniIconsRed" },
        ["external"] = { glyph = "󰉋", hl = "MiniIconsRed" },
        ["tmp"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["temp"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["cache"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["log"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["logs"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["storage"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["data"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["database"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["db"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["migrations"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["migration"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["seeds"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["seed"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["fixtures"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["fixture"] = { glyph = "󰉋", hl = "MiniIconsGrey" },
        ["locales"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["locale"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["i18n"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["translations"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["translation"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["lang"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["languages"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
        ["language"] = { glyph = "󰉋", hl = "MiniIconsYellow" },
      },
    },
  },
}
